### ISSUE TITLE
Readme Translation

### ISSUE THREAD

**Issue by Gouvernathor** [AgentAlpha81/RGB-Split#1]
This seems super cool, could you translate the readme file to english ?
I'm interested in using it for my ChromaGlitch effect and make it more efficient, but I'm not sure how to use it.

**Comment by AgentAlpha81** [comment]
Thank you for your interest in the project. I'll start translating the description as soon as I have free time.
Just add the shader to the transform as shown in the screenshots in the description. In the transform itself, specify the uniforms u_angle and u_intensity and set values to achieve the desired effect

**Comment by AgentAlpha81** [comment]
Translation is ready. Thanks to LaUwUrence =^_^=
